use std::collections::HashMap;
use std::fs;

use super::action_graph::{ActionNode, ActionType};
use super::Agent;
use crate::blob_store::BlobStore;
use crate::diff::applicator::apply_diff;
use crate::diff::format::EditBlock;

/// Executes tool calls, applies diffs, and runs commands.
/// Batches independent operations and summarizes results before returning them.
pub struct ExecutorAgent {
    /// Max number of independent tool calls to execute in one batch.
    pub batch_size: usize,
}

impl Default for ExecutorAgent {
    fn default() -> Self {
        Self { batch_size: 16 }
    }
}

impl ExecutorAgent {
    pub fn new() -> Self {
        Self::default()
    }

    /// Execute a single action node and return a summary of the result.
    pub fn execute(
        &self,
        node: &ActionNode,
        file_contents: &mut HashMap<String, String>,
        _store: &BlobStore,
    ) -> Result<String, String> {
        match &node.action_type {
            ActionType::Edit { file_path, .. } => {
                // In Phase 3, the actual diff is generated by the Editor agent before execution.
                // Here we just record that the file was touched.
                Ok(format!("Prepared edit context for {}", file_path))
            }
            ActionType::ToolCall { tool, arguments } => {
                self.run_tool(tool, arguments, file_contents)
            }
            ActionType::Validate { criteria } => {
                Ok(format!("Validation criteria: {}", criteria))
            }
            ActionType::Checkpoint => {
                // Checkpoint is handled by the Orchestrator; the Executor just acknowledges.
                Ok("Checkpoint acknowledged".to_string())
            }
        }
    }

    /// Apply a diff block to a file, updating both the in-memory `file_contents`
    /// and the blob store. Returns the new content.
    pub fn apply_edit_block(
        &self,
        file_path: &str,
        block: &EditBlock,
        file_contents: &mut HashMap<String, String>,
        store: &BlobStore,
    ) -> Result<String, String> {
        let content = file_contents
            .get(file_path)
            .cloned()
            .unwrap_or_default();
        let new_content = apply_diff(&content, block)
            .map_err(|e| format!("Diff application failed: {}", e))?;
        file_contents.insert(file_path.to_string(), new_content.clone());
        store.put(new_content.as_bytes().to_vec());
        Ok(new_content)
    }

    /// Run a batch of independent nodes and summarize their results.
    pub fn execute_batch(
        &self,
        nodes: &[&ActionNode],
        file_contents: &mut HashMap<String, String>,
        store: &BlobStore,
    ) -> HashMap<String, Result<String, String>> {
        let mut results = HashMap::new();
        for node in nodes {
            let result = self.execute(node, file_contents, store);
            results.insert(node.id.clone(), result);
        }
        results
    }

    fn run_tool(
        &self,
        tool: &str,
        arguments: &HashMap<String, String>,
        file_contents: &mut HashMap<String, String>,
    ) -> Result<String, String> {
        match tool {
            "read_file" => {
                let path = arguments.get("path").ok_or("Missing 'path' argument")?;
                let content = fs::read_to_string(path)
                    .or_else(|_| {
                        file_contents.get(path).cloned().ok_or_else(|| {
                            format!("File not found: {}", path)
                        })
                    })?;
                // Summarize: return first 20 lines + total line count.
                let lines: Vec<&str> = content.lines().collect();
                let preview: Vec<String> = lines
                    .iter()
                    .take(20)
                    .map(|s| s.to_string())
                    .collect();
                Ok(format!(
                    "{} ({} lines)\n{}",
                    path,
                    lines.len(),
                    preview.join("\n")
                ))
            }
            "write_file" => {
                let path = arguments.get("path").ok_or("Missing 'path' argument")?;
                let content = arguments.get("content").ok_or("Missing 'content' argument")?;
                file_contents.insert(path.to_string(), content.to_string());
                Ok(format!("Wrote {} ({} bytes)", path, content.len()))
            }
            "list_dir" => {
                let path = arguments.get("path").ok_or("Missing 'path' argument")?;
                let entries = fs::read_dir(path)
                    .map_err(|e| format!("Failed to list directory: {}", e))?
                    .filter_map(|entry| {
                        entry.ok().and_then(|e| {
                            e.file_name().into_string().ok()
                        })
                    })
                    .collect::<Vec<String>>();
                Ok(format!("{} entries in {}: {}", entries.len(), path, entries.join(", ")))
            }
            "search" | "grep" => {
                let query = arguments.get("query").ok_or("Missing 'query' argument")?;
                let mut matches = Vec::new();
                for (path, content) in file_contents.iter() {
                    for (line_num, line) in content.lines().enumerate() {
                        if line.contains(query) {
                            matches.push(format!("{}:{} {}", path, line_num + 1, line.trim()));
                            if matches.len() >= 20 {
                                break;
                            }
                        }
                    }
                    if matches.len() >= 20 {
                        break;
                    }
                }
                if matches.len() >= 20 {
                    matches.push("... (truncated after 20 matches)".to_string());
                }
                Ok(format!(
                    "Found {} matches for '{}'\n{}",
                    matches.len().saturating_sub(1),
                    query,
                    matches.join("\n")
                ))
            }
            "run_tests" => {
                // Placeholder: in a real system this would invoke the test runner.
                Ok("Tests: pass/fall summary not available in stub".to_string())
            }
            _ => Err(format!("Unknown tool: {}", tool)),
        }
    }

    /// Summarize raw tool results into a compact string for injection into agent context.
    pub fn summarize_results(&self, results: &HashMap<String, Result<String, String>>) -> String {
        let mut parts = Vec::new();
        for (id, result) in results {
            match result {
                Ok(summary) => parts.push(format!("[{}] OK: {}", id, summary)),
                Err(err) => parts.push(format!("[{}] ERR: {}", id, err)),
            }
        }
        parts.join("\n")
    }
}

impl Agent for ExecutorAgent {
    fn name(&self) -> &'static str {
        "ExecutorAgent"
    }
}
