use std::collections::HashMap;

use super::action_graph::{ActionNode, ActionType};
use super::tools::{ListDirTool, ReadFileTool, RunTestsTool, SearchTool, Tool, WriteFileTool};
use super::{Agent, ExecutorRole, SnapshotStore};
use crate::diff::applicator::apply_diff;
use crate::diff::format::EditBlock;

/// Executes tool calls, applies diffs, and runs commands.
/// Batches independent operations and summarizes results before returning them.
pub struct ExecutorAgent {
    /// Max number of independent tool calls to execute in one batch.
    pub batch_size: usize,
    tools: HashMap<String, Box<dyn Tool>>,
}

impl Default for ExecutorAgent {
    fn default() -> Self {
        Self::new()
    }
}

impl ExecutorAgent {
    pub fn new() -> Self {
        let mut tools: HashMap<String, Box<dyn Tool>> = HashMap::new();
        tools.insert("read_file".to_string(), Box::new(ReadFileTool));
        tools.insert("write_file".to_string(), Box::new(WriteFileTool));
        tools.insert("list_dir".to_string(), Box::new(ListDirTool));
        tools.insert("search".to_string(), Box::new(SearchTool));
        tools.insert("grep".to_string(), Box::new(SearchTool));
        tools.insert("run_tests".to_string(), Box::new(RunTestsTool));
        Self { batch_size: 16, tools }
    }

    /// Register a custom tool. Overwrites any existing tool with the same name.
    pub fn register_tool(&mut self, name: &str, tool: Box<dyn Tool>) {
        self.tools.insert(name.to_string(), tool);
    }

    /// Execute a single action node and return a summary of the result.
    pub fn execute(
        &self,
        node: &ActionNode,
        file_contents: &mut HashMap<String, String>,
        _store: &dyn SnapshotStore,
    ) -> Result<String, String> {
        match &node.action_type {
            ActionType::Edit { file_path, .. } => {
                // In Phase 3, the actual diff is generated by the Editor agent before execution.
                // Here we just record that the file was touched.
                Ok(format!("Prepared edit context for {}", file_path))
            }
            ActionType::ToolCall { tool, arguments } => {
                self.run_tool(tool, arguments, file_contents)
            }
            ActionType::Validate { criteria } => {
                Ok(format!("Validation criteria: {}", criteria))
            }
            ActionType::Checkpoint => {
                // Checkpoint is handled by the Orchestrator; the Executor just acknowledges.
                Ok("Checkpoint acknowledged".to_string())
            }
        }
    }

    /// Apply a diff block to a file, updating both the in-memory `file_contents`
    /// and the blob store. Returns the new content.
    pub fn apply_edit_block(
        &self,
        file_path: &str,
        block: &EditBlock,
        file_contents: &mut HashMap<String, String>,
        store: &dyn SnapshotStore,
    ) -> Result<String, String> {
        let content = file_contents
            .get(file_path)
            .cloned()
            .unwrap_or_default();
        let new_content = apply_diff(&content, block)
            .map_err(|e| format!("Diff application failed: {}", e))?;
        file_contents.insert(file_path.to_string(), new_content.clone());
        store.put(new_content.as_bytes().to_vec());
        Ok(new_content)
    }

    /// Run a batch of independent nodes and summarize their results.
    pub fn execute_batch(
        &self,
        nodes: &[&ActionNode],
        file_contents: &mut HashMap<String, String>,
        store: &dyn SnapshotStore,
    ) -> HashMap<String, Result<String, String>> {
        let mut results = HashMap::new();
        for node in nodes {
            let result = self.execute(node, file_contents, store);
            results.insert(node.id.clone(), result);
        }
        results
    }

    fn run_tool(
        &self,
        tool: &str,
        arguments: &HashMap<String, String>,
        file_contents: &mut HashMap<String, String>,
    ) -> Result<String, String> {
        self.tools
            .get(tool)
            .ok_or_else(|| format!("Unknown tool: {}", tool))?
            .execute(arguments, file_contents)
    }

    /// Summarize raw tool results into a compact string for injection into agent context.
    pub fn summarize_results(&self, results: &HashMap<String, Result<String, String>>) -> String {
        let mut parts = Vec::new();
        for (id, result) in results {
            match result {
                Ok(summary) => parts.push(format!("[{}] OK: {}", id, summary)),
                Err(err) => parts.push(format!("[{}] ERR: {}", id, err)),
            }
        }
        parts.join("\n")
    }
}

impl Agent for ExecutorAgent {
    fn name(&self) -> &'static str {
        "ExecutorAgent"
    }
}

impl ExecutorRole for ExecutorAgent {
    fn execute(
        &self,
        node: &ActionNode,
        file_contents: &mut HashMap<String, String>,
        store: &dyn SnapshotStore,
    ) -> Result<String, String> {
        ExecutorAgent::execute(self, node, file_contents, store)
    }

    fn execute_batch(
        &self,
        nodes: &[&ActionNode],
        file_contents: &mut HashMap<String, String>,
        store: &dyn SnapshotStore,
    ) -> HashMap<String, Result<String, String>> {
        ExecutorAgent::execute_batch(self, nodes, file_contents, store)
    }

    fn apply_edit_block(
        &self,
        file_path: &str,
        block: &EditBlock,
        file_contents: &mut HashMap<String, String>,
        store: &dyn SnapshotStore,
    ) -> Result<String, String> {
        ExecutorAgent::apply_edit_block(self, file_path, block, file_contents, store)
    }

    fn summarize_results(&self, results: &HashMap<String, Result<String, String>>) -> String {
        ExecutorAgent::summarize_results(self, results)
    }
}
